### Q 1.4

In [39]:
import numpy as np
X = np.array([[0,1,0,1],[3,3,1,1]]).T
y = np.array([1,1,0,0])
w0 = np.array([-2,1,0]).T
lamb = 0.07

In [51]:
addpath('./functions')
X = [0 3;1 3;0 1;1 1;];
y = [1;1;0;0];
X = [X, ones(4, 1)];
l = 0.07;
w0 = [-2;1;0];

s0 = sigmoid(X, w0);

w1 = w0 + inv(2*l*ones(3)+X'*diag(s0)*X)*(2*l*w0-X'*(y-s0));
s1 = sigmoid(X, w1);
w2 = w1 + inv(2*l*ones(3)+X'*diag(s1)*X)*(2*l*w1-X'*(y-s1));

In [75]:
def sigmoid(X, w):
    return 1/(1 + np.exp(-X @ w))

def Newton(X, y, lamb, max_iter, w):
    iter_cost = []
#     X = np.concatenate((X,np.ones((X.shape[0],1))),axis = 1)
    for i in range(max_iter):
        g = gradient(X,w,y,lamb)
        w = w - g
    return w

def gradient(X, w, y, lamb):
    g = -X.T.dot(y - sigmoid(X, w)) + 2 * lamb * w
    gg = np.linalg.inv(2*lamb*np.ones(3)+X.T@np.diag(sigmoid(X, w))@X)@g
    return gg 

In [76]:
# state the value of s0
X_c = np.concatenate((X,np.ones((X.shape[0],1))),axis = 1)
s0 = sigmoid(X_c,w0)
s0

array([0.95257413, 0.73105858, 0.73105858, 0.26894142])

In [77]:
# State the value of w1
max_iter = 1
w1 = Newton(X_c, y, lamb, max_iter, w0)
w1

array([-1.25039512,  1.45276462, -1.53745277])

In [78]:
# State the value of s1
s1 = sigmoid(X_c,w1)
s1

array([0.9437917 , 0.82784718, 0.47884061, 0.20831978])

In [79]:
max_iter = 2
w2 = Newton(X_c, y, lamb, max_iter, w0)
w2

array([-0.87605518,  1.60823428, -2.16803196])